/**
 * Produces a plausible ~6 months of accounts + transaction history for one
 * newly "linked" institution. This is the seam where a real Plaid/bank-data
 * adapter would eventually plug in (see BankProvider in
 * lib/store/FinanceContext.tsx) -- everything downstream (budgets, trends,
 * net worth) only depends on the shapes in lib/types.ts, not on how the data
 * was produced.
 *
 * Recurring bills/subscriptions still come from an explicit template list
 * below (`templates`) -- that's the easiest way to generate *believable*
 * mock history (a rent charge that actually lands monthly, a paycheck that
 * actually lands biweekly). What this file does NOT do anymore is hand that
 * template list back out as `RecurringSeries[]` -- recurring detection is a
 * real algorithm now (`lib/utils/recurring.ts`, `detectRecurringSeries()`)
 * that runs live over whatever transactions actually exist, so it works
 * identically for this generator's output, hand-entered transactions, and
 * CSV imports, instead of only working for accounts this file created.
 */
import type { Account, AccountType, RecurringCadence, SyncStatus, Transaction } from '@/lib/types';
import { addDays, addMonths, isoDate, startOfMonth } from '@/lib/utils/date';
import { makeRng, pick, randFloat, randInt } from '@/lib/utils/rng';

/**
 * Rolls a plausible connection-health state for a newly "linked" account.
 * There's no real bank connection behind this yet, so this exists purely to
 * make the sync-status UI (badges, the "needs attention" banner, the
 * refresh action) demonstrable from a fresh install, across a realistic mix
 * of states -- not to simulate an actual outage. A real provider adapter
 * would set these fields from its own webhook/poll results instead.
 */
function rollSyncState(rng: () => number): { syncStatus: SyncStatus; lastSyncedAt: string } {
  const roll = rng();
  const now = Date.now();
  if (roll < 0.7) {
    const minutesAgo = randInt(rng, 1, 240);
    return { syncStatus: 'synced', lastSyncedAt: new Date(now - minutesAgo * 60_000).toISOString() };
  }
  if (roll < 0.92) {
    const daysAgo = randInt(rng, 2, 6);
    return { syncStatus: 'stale', lastSyncedAt: new Date(now - daysAgo * 86_400_000).toISOString() };
  }
  const daysAgo = randInt(rng, 9, 21);
  return { syncStatus: 'error', lastSyncedAt: new Date(now - daysAgo * 86_400_000).toISOString() };
}

const MONTHS_BACK = 6;

const GROCERY_MERCHANTS = ["Trader Joe's", 'Whole Foods', 'Safeway', 'Kroger', 'Costco Wholesale'];
const DINING_MERCHANTS = ['Blue Bottle Coffee', 'Chipotle', 'Sweetgreen', 'Local Pizza Co', 'Thai Basil', 'Corner Deli'];
const TRANSPORT_MERCHANTS = ['Uber', 'Lyft', 'Shell Gas', 'Chevron', 'City Transit Card'];
const SHOPPING_MERCHANTS = ['Amazon', 'Target', 'Nike.com', 'IKEA', 'Best Buy'];
const ENTERTAINMENT_MERCHANTS = ['AMC Theatres', 'Steam', 'Ticketmaster', 'Spotify Concerts'];
const PERSONAL_CARE_MERCHANTS = ['Great Clips', 'Sephora', 'Local Spa'];
const HEALTH_ONEOFF_MERCHANTS = ['CVS Pharmacy', 'Urgent Care Copay', 'Dental Associates'];
const TRAVEL_MERCHANTS = ['United Airlines', 'Airbnb', 'Marriott Hotels', 'Delta Air Lines'];
const SUBSCRIPTION_CATALOG: { name: string; amount: number }[] = [
  { name: 'Netflix', amount: -15.99 },
  { name: 'Spotify Premium', amount: -11.99 },
  { name: 'iCloud+', amount: -2.99 },
  { name: 'The New York Times', amount: -17 },
  { name: 'Notion Plus', amount: -10 },
  { name: 'Hulu', amount: -12.99 },
  { name: 'Adobe Creative Cloud', amount: -54.99 },
];

interface RecurringTemplate {
  merchantName: string;
  categoryId: string;
  cadence: RecurringCadence;
  amount: number; // fixed or base amount
  accountKind: 'checking' | 'credit';
}

export interface GeneratedBankData {
  accounts: Account[];
  transactions: Transaction[];
}

export interface GenerateBankDataOptions {
  /** Fixed "life bills" -- rent, utilities, payroll, gym -- only make sense
   * coming from one household's accounts once. Without this gate, linking
   * a second institution independently re-rolled its own "Skyline
   * Apartments" rent and "Employer Payroll" paycheck, so anyone who linked
   * two banks in the demo ended up with two rents and two salaries, and
   * `detectRecurringSeries()` (correctly) reported both -- realistic single
   * accounts, unrealistic combination. Defaults to `true` so a lone linked
   * institution behaves exactly as before. */
  includeFixedBills?: boolean;
  /** Subscription merchant names already generated by a previously linked
   * institution this session, so a second bank's independently-rolled 3-5
   * subscriptions can't re-pick "Netflix" and produce two identical
   * charges. */
  excludeSubscriptionNames?: string[];
}

export function generateBankData(institutionId: string, seed: number, options: GenerateBankDataOptions = {}): GeneratedBankData {
  const { includeFixedBills = true, excludeSubscriptionNames = [] } = options;
  const rng = makeRng(seed);
  const idPrefix = `${institutionId}-${seed}`;

  const hasSavings = rng() < 0.85;
  const hasCredit = rng() < 0.75;

  const checking: Account = {
    id: `${idPrefix}-checking`,
    institutionId,
    name: 'Everyday Checking',
    mask: String(randInt(rng, 1000, 9999)).slice(-4),
    type: 'checking',
    balance: 0, // filled in after transactions are generated
    source: 'linked',
    ...rollSyncState(rng),
  };

  const savings: Account | null = hasSavings
    ? {
        id: `${idPrefix}-savings`,
        institutionId,
        name: 'High-Yield Savings',
        mask: String(randInt(rng, 1000, 9999)).slice(-4),
        type: 'savings',
        balance: 0,
        apy: randFloat(rng, 3.8, 4.9, 1),
        source: 'linked',
        ...rollSyncState(rng),
      }
    : null;

  const creditLimit = randInt(rng, 4, 15) * 1000;
  const credit: Account | null = hasCredit
    ? {
        id: `${idPrefix}-credit`,
        institutionId,
        name: 'Rewards Credit Card',
        mask: String(randInt(rng, 1000, 9999)).slice(-4),
        type: 'credit_card',
        balance: 0,
        creditLimit,
        source: 'linked',
        ...rollSyncState(rng),
      }
    : null;

  const spendAccountId = credit?.id ?? checking.id;

  const monthlyIncome = randInt(rng, 3600, 8200);
  const paycheckAmount = Math.round((monthlyIncome / 2) * 100) / 100;

  const templates: RecurringTemplate[] = includeFixedBills
    ? [
        { merchantName: 'Employer Payroll', categoryId: 'income', cadence: 'biweekly', amount: paycheckAmount, accountKind: 'checking' },
        { merchantName: 'Skyline Apartments', categoryId: 'housing', cadence: 'monthly', amount: -randInt(rng, 1300, 2900), accountKind: 'checking' },
        { merchantName: 'Pacific Power & Light', categoryId: 'utilities', cadence: 'monthly', amount: -randInt(rng, 60, 160), accountKind: 'checking' },
        { merchantName: 'Metro Fiber Internet', categoryId: 'utilities', cadence: 'monthly', amount: -randInt(rng, 55, 95), accountKind: 'checking' },
        { merchantName: 'Wireless Carrier', categoryId: 'utilities', cadence: 'monthly', amount: -randInt(rng, 45, 95), accountKind: 'checking' },
        { merchantName: 'Equinox Fitness', categoryId: 'health', cadence: 'monthly', amount: -randInt(rng, 35, 85), accountKind: 'checking' },
      ]
    : [];

  const excludeSet = new Set(excludeSubscriptionNames.map(n => n.toLowerCase()));
  const availableSubscriptions = SUBSCRIPTION_CATALOG.filter(s => !excludeSet.has(s.name.toLowerCase()));
  const subCount = Math.min(randInt(rng, 3, 5), availableSubscriptions.length);
  const shuffled = [...availableSubscriptions].sort(() => rng() - 0.5).slice(0, subCount);
  for (const sub of shuffled) {
    templates.push({ merchantName: sub.name, categoryId: 'subscriptions', cadence: 'monthly', amount: sub.amount, accountKind: 'credit' });
  }

  // Design-audit pass: the loop below always walks a template forward right
  // up to `new Date()`, so *every* recurring series' most recent occurrence
  // was, by construction, never more than one cadence period old -- meaning
  // `detectRecurringSeries()` could never classify one as 'late' or
  // 'overdue' (see lib/utils/insights.ts's statusFor()) from generated data.
  // That status/color/copy was entirely unverified by anything short of
  // hand-editing localStorage, and unseen by anyone just clicking through
  // the demo (App Store screenshots included). Letting exactly one
  // subscription (never rent/payroll/utilities -- a lapsed *paycheck*
  // reads as a crisis, a lapsed streaming subscription reads as Tuesday)
  // skip its most recent expected charge below simulates a cancelled-but-
  // not-yet-noticed subscription, which is realistic on its own merits, not
  // just a test hook.
  const lapsedMerchant = shuffled.length > 0 && rng() < 0.6 ? shuffled[0].name : null;

  const transactions: Transaction[] = [];
  let txCounter = 0;
  const nextTxId = () => `${idPrefix}-tx-${txCounter++}`;

  const today = startOfMonth(new Date());
  const rangeStart = addMonths(today, -MONTHS_BACK);

  // Recurring bills + paychecks, walked forward by cadence across the window.
  for (const tpl of templates) {
    const accountId = tpl.accountKind === 'credit' ? spendAccountId : checking.id;
    let cursor = new Date(rangeStart);
    // Nudge each template onto its own day-of-month so a rendered list
    // doesn't show five bills landing on the exact same date.
    cursor = addDays(cursor, randInt(rng, 0, 27));
    const templateStartIdx = transactions.length;

    while (cursor < new Date()) {
      const jitter = tpl.cadence === 'biweekly' ? 0 : randInt(rng, -1, 1);
      // Subscription prices don't fluctuate month to month -- charging the
      // exact template amount every time (unlike variable bills below) is
      // what makes them "subscriptions" rather than "variable expenses,"
      // and it's what a real recurring-detector should be able to key off.
      const amount =
        tpl.categoryId === 'income'
          ? tpl.amount + randInt(rng, -50, 120)
          : tpl.categoryId === 'subscriptions'
            ? tpl.amount
            : tpl.amount + randFloat(rng, -3, 3, 2);
      transactions.push({
        id: nextTxId(),
        accountId,
        date: isoDate(addDays(cursor, jitter)),
        merchantName: tpl.merchantName,
        rawDescription: tpl.merchantName.toUpperCase().replace(/[^A-Z0-9]/g, ' ').trim(),
        amount: Math.round(amount * 100) / 100,
        categoryId: tpl.categoryId,
      });
      cursor = tpl.cadence === 'biweekly' ? addDays(cursor, 14) : tpl.cadence === 'weekly' ? addDays(cursor, 7) : addMonths(cursor, 1);
    }

    // Drop only the single most recent occurrence, and only once there's
    // still a comfortable margin over MIN_OCCURRENCES (2) left in
    // lib/utils/recurring.ts -- six months of a monthly cadence leaves 5+,
    // plenty to still classify correctly as recurring.
    if (tpl.merchantName === lapsedMerchant && transactions.length - templateStartIdx >= 3) {
      transactions.pop();
    }
  }

  // Discretionary spend, scattered per month.
  const discretionary: { merchants: string[]; categoryId: string; perMonth: [number, number]; amount: [number, number] }[] = [
    { merchants: GROCERY_MERCHANTS, categoryId: 'groceries', perMonth: [3, 5], amount: [25, 160] },
    { merchants: DINING_MERCHANTS, categoryId: 'dining', perMonth: [6, 12], amount: [8, 75] },
    { merchants: TRANSPORT_MERCHANTS, categoryId: 'transport', perMonth: [3, 8], amount: [8, 60] },
    { merchants: SHOPPING_MERCHANTS, categoryId: 'shopping', perMonth: [2, 5], amount: [15, 220] },
    { merchants: ENTERTAINMENT_MERCHANTS, categoryId: 'entertainment', perMonth: [1, 3], amount: [10, 90] },
    { merchants: PERSONAL_CARE_MERCHANTS, categoryId: 'personal_care', perMonth: [0, 2], amount: [20, 120] },
  ];

  for (let m = 0; m < MONTHS_BACK; m++) {
    const monthStart = addMonths(rangeStart, m);
    for (const group of discretionary) {
      const count = randInt(rng, group.perMonth[0], group.perMonth[1]);
      for (let i = 0; i < count; i++) {
        const day = randInt(rng, 0, 27);
        transactions.push({
          id: nextTxId(),
          accountId: spendAccountId,
          date: isoDate(addDays(monthStart, day)),
          merchantName: pick(rng, group.merchants),
          rawDescription: 'CARD PURCHASE',
          amount: -randFloat(rng, group.amount[0], group.amount[1]),
          categoryId: group.categoryId,
        });
      }
    }

    // Rare bigger one-offs.
    if (rng() < 0.35) {
      transactions.push({
        id: nextTxId(),
        accountId: spendAccountId,
        date: isoDate(addDays(monthStart, randInt(rng, 0, 27))),
        merchantName: pick(rng, HEALTH_ONEOFF_MERCHANTS),
        rawDescription: 'CARD PURCHASE',
        amount: -randFloat(rng, 20, 280),
        categoryId: 'health',
      });
    }
    if (rng() < 0.22) {
      transactions.push({
        id: nextTxId(),
        accountId: spendAccountId,
        date: isoDate(addDays(monthStart, randInt(rng, 0, 27))),
        merchantName: pick(rng, TRAVEL_MERCHANTS),
        rawDescription: 'CARD PURCHASE',
        amount: -randFloat(rng, 180, 1200),
        categoryId: 'travel',
      });
    }
    if (rng() < 0.18) {
      transactions.push({
        id: nextTxId(),
        accountId: checking.id,
        date: isoDate(addDays(monthStart, randInt(rng, 0, 27))),
        merchantName: rng() < 0.5 ? 'Client Payment' : 'Year-End Bonus',
        rawDescription: 'DEPOSIT',
        amount: randFloat(rng, 150, 900),
        categoryId: 'income',
      });
    }
    if (credit && rng() < 0.15) {
      transactions.push({
        id: nextTxId(),
        accountId: credit.id,
        date: isoDate(addDays(monthStart, randInt(rng, 25, 28))),
        merchantName: 'Interest Charge',
        rawDescription: 'INTEREST CHARGE',
        amount: -randFloat(rng, 8, 45),
        categoryId: 'fees',
      });
    }
  }

  transactions.sort((a, b) => (a.date < b.date ? 1 : -1));

  // Derive current balances from a baseline plus everything that happened,
  // so the ending balance is a consequence of the history, not a made-up
  // number sitting next to it.
  const sumFor = (accountId: string) => transactions.filter(t => t.accountId === accountId).reduce((s, t) => s + t.amount, 0);

  checking.balance = Math.round((randFloat(rng, 800, 2600) + sumFor(checking.id)) * 100) / 100;
  if (checking.balance < 150) checking.balance = randFloat(rng, 400, 900); // keep it from reading as overdrawn by default

  if (savings) {
    savings.balance = Math.round((randFloat(rng, 3000, 18000) + sumFor(savings.id)) * 100) / 100;
  }
  if (credit) {
    const owed = randFloat(rng, 50, 400) - sumFor(credit.id); // spend is negative, so subtracting increases what's owed
    credit.balance = Math.max(0, Math.round(Math.min(owed, creditLimit * 0.85) * 100) / 100);
  }

  const accounts: Account[] = [checking, savings, credit].filter((a): a is Account => a !== null);

  return { accounts, transactions };
}

export function defaultBudgets(): { categoryId: string; monthlyLimit: number }[] {
  return [
    { categoryId: 'groceries', monthlyLimit: 500 },
    { categoryId: 'dining', monthlyLimit: 350 },
    { categoryId: 'transport', monthlyLimit: 200 },
    { categoryId: 'shopping', monthlyLimit: 250 },
    { categoryId: 'entertainment', monthlyLimit: 120 },
    { categoryId: 'personal_care', monthlyLimit: 100 },
    { categoryId: 'subscriptions', monthlyLimit: 80 },
  ];
}

export type { AccountType };
